Repository softeerbootcamp4th/Team6-AwesomeOrange-FE, pull requests merged in 2024-07, with the labels that each got.

#5 [build] eslint와 prettier 관련 설정
  .eslintrc.cjs
  .prettierrc
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/index.css
Labels: feat

#6 [build] Static Site Generation 세팅 및 자동 배포 및 통합(CI/CD) 설정 (#3)
  .github/workflows/check_lint.yaml
  .github/workflows/deploy_preview.yaml
  .github/workflows/deploy_production.yaml
  .gitignore
  index.html
  package-lock.json
  package.json
  prerender.js
  server.js
  src/common/ErrorBoundary.jsx
  src/common/Suspense.jsx
  src/main-client.jsx
  src/main-server.jsx
  src/main.jsx
Labels: feat

#36 [Feat] useScrollTransition 커스텀 훅 추가
  src/common/throttleRaf.js
  src/common/useScrollTransition.js
  src/common/utils.js
  src/index.css
  src/introSection/index.jsx
Labels: feat

#39 [refactor/build] 개발 서버 CSR로 변환
  package-lock.json
  package.json
  server.js
  src/main-client.jsx
Labels: fix, refactor

#40 [design] 색상, 그래디언트 재정의
  src/App.jsx
  src/index.css
  tailwind.config.js
  tailwind.redefine.js
Labels: style

#41 [feat] 고속충전 인터랙션 추가 (resolve #20)
  README.md
  package.json
  public/font/HyundaiSansTextKROTFBold.otf
  public/font/HyundaiSansTextKROTFMedium.otf
  public/font/HyundaiSansTextOffice-Medium.ttf
  public/font/HyundaiSansTextOffice-Medium.woff
  src/assets/property1.svg
  src/assets/property2.svg
  src/assets/property3.svg
  src/assets/property4.svg
  src/assets/property5.svg
  src/assets/react.svg
  src/index.css
  src/interactions/fastCharge/BatteryProgressBar.jsx
  src/interactions/fastCharge/FastChargeInteraction.jsx
  src/interactions/fastCharge/batteryStyle.module.css
  src/interactions/fastCharge/timer.svg
  src/interactions/fastCharge/useDialDrag.js
  tailwind.redefine.js
Labels: feat

#45 [feat] 보조금 인터랙션 추가 ( resolve #23 )
  package-lock.json
  package.json
  public/icons/property1.svg
  public/icons/property2.svg
  public/icons/property3.svg
  public/icons/property4.svg
  public/icons/property5.svg
  src/interactions/InteractionDescription.jsx
  src/interactions/distanceDriven/index.jsx
  src/interactions/distanceDriven/usePointDrag.js
  src/interactions/fastCharge/assets/timer.svg
  src/interactions/fastCharge/index.jsx
  src/interactions/fastCharge/useDialDrag.js
  src/interactions/subsidy/assets/coin.json
  src/interactions/subsidy/assets/dollor.svg
  src/interactions/subsidy/index.jsx
  src/interactions/univasalIsland/index.jsx
Labels: feat

#49 [feat] 서브타이틀과 화살표 추가
  src/introSection/index.jsx
  src/introSection/pointer.svg
Labels: feat

#48 [feat] V2L 인터랙션 구현 ( resolved #22 )
  src/common/ClientOnly.jsx
  src/common/Suspense.jsx
  src/interactions/fastCharge/batteryStyle.module.css
  src/interactions/univasalIsland/Phone.jsx
  src/interactions/univasalIsland/index.jsx
  src/interactions/univasalIsland/style.module.css
  src/interactions/v2l/Puzzle.jsx
  src/interactions/v2l/PuzzlePiece.jsx
  src/interactions/v2l/assets/car@1x.png
  src/interactions/v2l/assets/car@2x.png
  src/interactions/v2l/assets/pan.svg
  src/interactions/v2l/assets/panContainer@1x.png
  src/interactions/v2l/assets/panContainer@2x.png
  src/interactions/v2l/constants.js
  src/interactions/v2l/generateRandom.js
  src/interactions/v2l/index.jsx
  src/interactions/v2l/style.module.css
  src/interactions/v2l/utils.js
Labels: feat

#50 [feat] 헤더바 구현
  src/App.jsx
  src/header/index.jsx
  src/header/index.module.css
Labels: feat

#52 [refactor] 헤더바 개선
  src/header/index.jsx
Labels: fix, refactor

#53 [refactor] 헤더바 개선
  src/header/index.jsx
Labels: refactor

#54 [feat] QnA 섹션, 푸터 섹션 구현, 약간의 SEO 개선
  index.html
  public/robots.txt
  src/App.jsx
  src/footer/index.jsx
  src/header/index.jsx
  src/interactions/distanceDriven/index.jsx
  src/interactions/subsidy/index.jsx
  src/interactions/v2l/Puzzle.jsx
  src/introSection/LineHighlight.jsx
  src/introSection/index.jsx
  src/introSection/index.module.css
  src/introSection/vector.svg
  src/qna/QnAArticle.jsx
  src/qna/assets/arrow.svg
  src/qna/content.json
  src/qna/index.jsx
  tailwind.redefine.js
Labels: feat, style
