Repository softeerbootcamp4th/Team6-AwesomeOrange-FE, pull requests merged in 2024-08, with the labels that each got.

#56 [feat] 차량 간단정보 구현
  public/carimg1.png
  public/carimg2.png
  public/carimg3.png
  public/carimg4.png
  public/carimg5.png
  src/App.jsx
  src/simpleInformation/contentList.json
  src/simpleInformation/contentSection.jsx
  src/simpleInformation/contentSection.module.css
  src/simpleInformation/index.jsx
Labels: feat

#57 [feat] 모달 인터페이스 구현 ( resolve #55 )
  src/App.jsx
  src/modal/modal.jsx
  src/modal/openModal.js
  src/modal/store.js
  src/modal/useBodyScrollLock.js
Labels: feat

#59 [feat] 차량 상세정보 섹션 구현
  package-lock.json
  package.json
  public/detail_V2L.png
  public/detail_distance.png
  public/detail_electric.png
  public/detail_money.png
  public/detail_univasal.png
  public/sketchLine.svg
  src/App.jsx
  src/common/useSwiperState.js
  src/detailInformation/DetailItem.jsx
  src/detailInformation/DetailSwiper.jsx
  src/detailInformation/assets/decoration.svg
  src/detailInformation/assets/left.svg
  src/detailInformation/assets/right.svg
  src/detailInformation/content.json
  src/detailInformation/index.jsx
  src/index.css
  src/main-client.jsx
  src/simpleInformation/contentList.json
  src/simpleInformation/contentSection.jsx
  src/simpleInformation/contentSection.module.css
  src/simpleInformation/index.jsx
Labels: feat

#60 [feat] 타이머 구현과 버그 수정
  src/introSection/car-spin-small.webm
  src/introSection/car-spin.mp4
  src/introSection/car-spin.webm
  src/introSection/index.jsx
  src/introSection/index.module.css
Labels: fix, feat

#61 [feat] MSW 세팅 및 http 통신 헬퍼 함수 추가
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/common/fetchServer.js
  src/common/wrapPromise.js
  src/main-client.jsx
  src/mock.js
Labels: feat

#63 [feat] 기대평 무한 캐러셀 구현
  public/icons/error.svg
  src/App.jsx
  src/comment/assets/decoration.svg
  src/comment/autoScrollCarousel/index.jsx
  src/comment/autoScrollCarousel/useAutoCarousel.js
  src/comment/commentCarousel/CommentCarousel.jsx
  src/comment/commentCarousel/CommentCarouselError.jsx
  src/comment/commentCarousel/CommentCarouselSkeleton.jsx
  src/comment/commentCarousel/index.jsx
  src/comment/index.jsx
  src/comment/mock.js
  src/common/Spinner.jsx
  src/common/useMountDragEvent.js
  src/interactions/distanceDriven/index.jsx
  src/introSection/index.module.css
  src/main-client.jsx
  src/mock.js
Labels: fix, feat

#65 [design] 반응형 관련 스타일 수정
  src/introSection/index.jsx
Labels: style

#66 [fix] 무한 캐러셀 관련 버그 수정
  src/comment/autoScrollCarousel/useAutoCarousel.js
  src/comment/commentCarousel/index.jsx
Labels: fix

#68 [feat] 스크롤 관련 구현
  package-lock.json
  src/App.jsx
  src/comment/index.jsx
  src/detailInformation/index.jsx
  src/header/index.jsx
  src/interactions/index.jsx
  src/introSection/index.jsx
  src/scroll/scrollTo.js
  src/scroll/store.js
  src/scroll/useSectionInitialize.js
  src/simpleInformation/index.jsx
Labels: feat

#69 [feat] 스크롤 따라 헤더바 상태 변경되는 것 구현
  src/comment/index.jsx
  src/detailInformation/index.jsx
  src/header/index.jsx
  src/interactions/index.jsx
  src/scroll/store.js
  src/scroll/useSectionInitialize.js
  src/simpleInformation/index.jsx
Labels: feat

#71 [feat] 기대평 작성 기능 추가
  public/icons/register@1x.png
  public/icons/register@2x.png
  public/icons/waiting@1x.png
  public/icons/waiting@2x.png
  src/auth/AuthCode/InputWithTimer.jsx
  src/auth/AuthCode/index.jsx
  src/auth/AuthCode/submitAuthCode.js
  src/auth/AuthCode/useTimer.js
  src/auth/AuthModal.jsx
  src/auth/AuthSecondSection.jsx
  src/auth/InfoInput/index.jsx
  src/auth/UserFind/index.jsx
  src/auth/UserFind/requestLogin.js
  src/auth/Welcome/index.jsx
  src/auth/mock.js
  src/auth/requestAuthCode.js
  src/auth/tokenSaver.js
  src/comment/commentForm/index.jsx
  src/comment/index.jsx
  src/comment/mock.js
  src/comment/modals/CommentNegativeModal.jsx
  src/comment/modals/CommentNoUserModal.jsx
  src/comment/modals/CommentSuccessModal.jsx
  src/common/IntervalController.js
  src/common/NoServerModal.jsx
  src/common/constants.js
  src/common/fetchServer.js
  src/detailInformation/DetailSwiper.jsx
  src/detailInformation/index.jsx
  src/header/index.jsx
  src/header/index.module.css
  src/interactions/distanceDriven/index.jsx
  src/interactions/fastCharge/index.jsx
  src/interactions/subsidy/index.jsx
  src/introSection/index.jsx
  src/main-client.jsx
  src/scroll/useSectionInitialize.js
  tailwind.redefine.js
Labels: feat

#72 [feat] 인터랙션 페이지 정적인 부분 작성
  package-lock.json
  package.json
  public/gift_car.png
  public/gift_jeju.png
  public/gift_portable.png
  public/icons/check-mint.svg
  src/interactions/GiftDetail.jsx
  src/interactions/IntroductionDetail.jsx
  src/interactions/TabBar.jsx
  src/interactions/content.json
  src/interactions/index.jsx
  src/interactions/star.svg
  vite.config.js
Labels: feat

#75 [feat] 인터랙션 슬라이드 구현
  public/active1.png
  public/active2.png
  public/active3.png
  public/active4.png
  public/active5.png
  public/icons/rect1.svg
  public/icons/rect2.svg
  public/icons/rect3.svg
  public/icons/rect4.svg
  public/icons/rect5.svg
  public/inactive1.png
  public/inactive2.png
  public/inactive3.png
  public/inactive4.png
  public/inactive5.png
  src/interactions/GiftDetail.jsx
  src/interactions/InteractionSlide.jsx
  src/interactions/TapBar.jsx
  src/interactions/content.json
  src/interactions/fastCharge/index.jsx
  src/interactions/index.jsx
Labels: feat

#76 [feat] 로그인 상태 구현
  .eslintrc.cjs
  src/App.jsx
  src/auth/AuthCode/index.jsx
  src/auth/AuthCode/submitAuthCode.js
  src/auth/AuthModal.jsx
  src/auth/UserFind/index.jsx
  src/auth/UserFind/requestLogin.js
  src/auth/requestAuthCode.js
  src/auth/store.js
  src/comment/commentCarousel/CommentCarouselSkeleton.jsx
  src/comment/commentCarousel/index.jsx
  src/comment/commentForm/SubmitButton/index.jsx
  src/comment/commentForm/index.jsx
  src/comment/mock.js
  src/common/DelaySkeleton.jsx
  src/common/dataFetch/fetchServer.js
  src/common/dataFetch/wrapPromise.js
  src/header/AuthButtonSection.jsx
  src/header/index.jsx
  src/interactions/IntroductionDetail.jsx
  src/interactions/TapBar.jsx
  src/interactions/content.json
  src/main-client.jsx
Labels: feat, refactor

#80 [feat] 선착순 이벤트 일부 구현
  src/App.jsx
  src/auth/mock.js
  src/comment/commentCarousel/CommentCarousel.jsx
  src/comment/commentCarousel/index.jsx
  src/common/ClientOnly.jsx
  src/common/constants.js
  src/common/dataFetch/fetchServer.js
  src/common/dataFetch/getQuery.js
  src/common/dataFetch/use.js
  src/common/dataFetch/wrapPromise.js
  src/common/utils.js
  src/eventDescription/EventDetail.jsx
  src/eventDescription/makeHighlight.jsx
  src/fcfs/FcfsDescription.jsx
  src/fcfs/cardGame/Card.jsx
  src/fcfs/cardGame/CardGame.jsx
  src/fcfs/cardGame/CardGameTitle.jsx
  src/fcfs/cardGame/assets/correct@1x.png
  src/fcfs/cardGame/assets/correct@2x.png
  src/fcfs/cardGame/assets/failed@1x.png
  src/fcfs/cardGame/assets/failed@2x.png
  src/fcfs/cardGame/assets/hidden@1x.png
  src/fcfs/cardGame/assets/hidden@2x.png
  src/fcfs/cardGame/index.jsx
  src/fcfs/cardGame/style.module.css
  src/fcfs/constants.js
  src/fcfs/content.json
  src/fcfs/countdown/CountStarter.jsx
  src/fcfs/countdown/CountdownController.js
  src/fcfs/index.jsx
  src/fcfs/mock.js
  src/fcfs/store.js
  src/mock.js
Labels: feat, refactor

#79 [feat] 인터랙션 모달 구현
  public/icons/close-white.svg
  public/icons/left-arrow.svg
  public/icons/polygon-tri.svg
  public/icons/refresh.svg
  src/interactions/InteractionAnswer.jsx
  src/interactions/InteractionAnswer.module.css
  src/interactions/InteractionModal.jsx
  src/interactions/InteractionSlide.jsx
  src/interactions/content.json
  src/interactions/index.jsx
Labels: feat

#82 [feat] 선착순 이벤트 당첨 모달 추가
  public/icons/lose@1x.png
  public/icons/lose@2x.png
  public/icons/win@1x.png
  public/icons/win@2x.png
  src/fcfs/cardGame/Card.jsx
  src/fcfs/cardGame/CardGame.jsx
  src/fcfs/cardGame/style.module.css
  src/fcfs/mock.js
  src/fcfs/modals/FcfsInvalidModal.jsx
  src/fcfs/modals/FcfsLoseModal.jsx
  src/fcfs/modals/FcfsWinModal.jsx
  src/introSection/index.jsx
  src/introSection/notifier/FcfsNotifierCountdown.jsx
  src/introSection/notifier/index.jsx
Labels: feat, style

#83 [feat] 인터랙션 모달 분기 처리
  src/interactions/GiftDetail.jsx
  src/interactions/InteractionAnswer.jsx
  src/interactions/InteractionModal.jsx
  src/interactions/InteractionSlide.jsx
  src/interactions/IntroductionDetail.jsx
  src/interactions/TapBar.jsx
  src/interactions/index.jsx
Labels: feat, style

#90 [build] 어드민 페이지 기본 세팅
  admin.html
  build.js
  package-lock.json
  package.json
  prerender.js
  public/images/active1.png
  public/images/active2.png
  public/images/active3.png
  public/images/active4.png
  public/images/active5.png
  public/images/carimg1.png
  public/images/carimg2.png
  public/images/carimg3.png
  public/images/carimg4.png
  public/images/carimg5.png
  public/images/gift_car.png
  public/images/gift_jeju.png
  public/images/gift_portable.png
  public/images/inactive1.png
  public/images/inactive2.png
  public/images/inactive3.png
  public/images/inactive4.png
  public/images/inactive5.png
  src/adminPage/App.jsx
  src/adminPage/index.css
  src/adminPage/main-client.jsx
  src/adminPage/main-server.jsx
  src/adminPage/mock.js
  src/common/constants.js
  src/common/dataFetch/tokenSaver.js
  src/common/modal/modal.jsx
  src/common/utils.js
  src/mainPage/features/interactions/content.json
  src/mainPage/features/interactions/description/InteractionSlide.jsx
  src/mainPage/features/interactions/modal/InteractionAnswer.jsx
  src/mainPage/features/interactions/modal/InteractionModal.jsx
  src/mainPage/features/introSection/index.jsx
  src/mainPage/features/simpleInformation/content.json
  src/mainPage/features/simpleInformation/contentSection.jsx
  src/mainPage/shared/auth/store.js
  src/mainPage/shared/realtimeEvent/getEventDateState.js
  src/mainPage/shared/scroll/constants.js
  vite-devRouter.js
  vite.config.js
Labels: feat

#91 [feat, refactor] mock 서버와 통신 관련 구체화
  src/common/constants.js
  src/mainPage/features/interactions/index.jsx
  src/mainPage/features/interactions/mock.js
  src/mainPage/features/interactions/modal/InteractionAnswer.jsx
  src/mainPage/features/interactions/modal/InteractionModal.jsx
  src/mainPage/mock.js
Labels: feat, refactor

#92 [fix] EVENT_ID 누락 수정
  src/common/constants.js
Labels: fix

#94 [refactor, chore] 인터랙션 페이지 유저플로우에 맞게 수정
  src/mainPage/features/interactions/description/InteractionSlide.jsx
  src/mainPage/features/interactions/modal/InteractionAnswer.jsx
Labels: chore, refactor

#93 [feat] 어드민 페이지 로그인 기능 추가, 자동 로그아웃 로직 구현
  src/adminPage/App.jsx
  src/adminPage/mock.js
  src/adminPage/pages/EventsPage.jsx
  src/adminPage/pages/LoginPage.jsx
  src/adminPage/pages/ProtectedRoute.jsx
  src/adminPage/pages/RootRoute.jsx
  src/adminPage/shared/auth/LoginSection.jsx
  src/adminPage/shared/auth/mock.js
  src/adminPage/shared/auth/store.js
  src/adminPage/shared/components/Container.jsx
  src/adminPage/shared/components/NavBar.jsx
  src/adminPage/shared/components/NavBarItem.jsx
  src/common/dataFetch/fetchServer.js
  src/common/dataFetch/initLogoutMiddleware.js
  src/mainPage/App.jsx
  src/mainPage/features/fcfs/mock.js
Labels: feat

#95 [feat] 어드민 페이지 이벤트 목록 페이지 부분 구현
  src/adminPage/App.jsx
  src/adminPage/features/eventList/Filter.jsx
  src/adminPage/features/eventList/SearchBar.jsx
  src/adminPage/features/eventList/TableHeader.jsx
  src/adminPage/features/eventList/TableSorter.jsx
  src/adminPage/features/eventList/assets/downArrow.svg
  src/adminPage/features/eventList/assets/search.svg
  src/adminPage/features/eventList/assets/upArrow.svg
  src/adminPage/features/eventList/index.jsx
  src/adminPage/features/eventList/reducer.js
  src/adminPage/features/eventList/tableStyle.js
  src/adminPage/pages/EventsPage.jsx
  src/adminPage/pages/ProtectedRoute.jsx
  src/adminPage/shared/auth/store.js
  src/adminPage/shared/components/Container.jsx
  src/common/components/Checkbox.jsx
  src/mainPage/features/interactions/description/InteractionSlide.jsx
  src/mainPage/shared/auth/InfoInput/index.jsx
Labels: feat

#96 [feat] 어드민 기대평 이벤트 검색 일부 구현
  public/icons/search.png
  src/adminPage/App.jsx
  src/adminPage/pages/CommentsPage.jsx
  src/mainPage/features/interactions/modal/InteractionAnswer.jsx
Labels: feat

#98 [feat] 어드민 페이지 이벤트 목록 구현
  .github/workflows/deploy_preview.yaml
  .github/workflows/deploy_production.yaml
  src/adminPage/App.jsx
  src/adminPage/features/eventEdit/Container.jsx
  src/adminPage/features/eventEdit/index.jsx
  src/adminPage/features/eventList/DeleteButton.jsx
  src/adminPage/features/eventList/SearchBar.jsx
  src/adminPage/features/eventList/checkReducer.js
  src/adminPage/features/eventList/index.jsx
  src/adminPage/features/eventList/mock.js
  src/adminPage/features/eventList/queryReducer.js
  src/adminPage/features/eventList/table/SearchResultBody.jsx
  src/adminPage/features/eventList/table/SearchResultItem.jsx
  src/adminPage/features/eventList/table/TableHeader.jsx
  src/adminPage/features/eventList/table/TableSorter.jsx
  src/adminPage/features/eventList/table/index.jsx
  src/adminPage/features/eventList/table/tableStyle.js
  src/adminPage/features/eventList/tableStyle.js
  src/adminPage/index.css
  src/adminPage/mock.js
  src/adminPage/pages/EventsCreatePage.jsx
  src/adminPage/pages/EventsDetailPage.jsx
  src/adminPage/pages/LoginPage.jsx
  src/adminPage/shared/components/Container.jsx
  src/adminPage/shared/components/Pagination.jsx
  src/adminPage/shared/modals/AlertModal.jsx
  src/adminPage/shared/modals/ConfirmModal.jsx
  src/adminPage/shared/serverTime/EventStatus.js
  src/adminPage/shared/serverTime/ServerTimeInitializer.jsx
  src/adminPage/shared/serverTime/mock.js
  src/adminPage/shared/serverTime/store.js
  src/common/components/Checkbox.jsx
  src/common/constants.js
  src/common/dataFetch/getQuery.js
  src/common/mock/utils.js
  src/common/utils.js
  src/mainPage/features/comment/commentCarousel/CommentCarousel.jsx
  src/mainPage/features/comment/mock.js
  src/mainPage/features/fcfs/cardGame/CardGame.jsx
  src/mainPage/features/fcfs/mock.js
  src/mainPage/shared/auth/InfoInput/index.jsx
  src/mainPage/shared/realtimeEvent/store.js
  vercel.json
Labels: feat, refactor

#99 [feat] 이벤트 생성 컴포넌트 리듀서 추가, 일부 기능구현
  src/adminPage/App.jsx
  src/adminPage/features/eventEdit/Container.jsx
  src/adminPage/features/eventEdit/DateTimeRangeInput.jsx
  src/adminPage/features/eventEdit/DrawInput.jsx
  src/adminPage/features/eventEdit/EventBaseDataInput.jsx
  src/adminPage/features/eventEdit/EventDetailInput.jsx
  src/adminPage/features/eventEdit/EventEditFetcher.jsx
  src/adminPage/features/eventEdit/FcfsInput.jsx
  src/adminPage/features/eventEdit/businessLogic/DrawGradeData.js
  src/adminPage/features/eventEdit/businessLogic/DrawPolicyData.js
  src/adminPage/features/eventEdit/businessLogic/FcfsData.js
  src/adminPage/features/eventEdit/businessLogic/makeUUID.js
  src/adminPage/features/eventEdit/businessLogic/reducer.js
  src/adminPage/features/eventEdit/index.jsx
  src/adminPage/features/eventList/table/SearchResultItem.jsx
  src/adminPage/features/eventList/table/index.jsx
  src/adminPage/pages/EventsCreatePage.jsx
  src/adminPage/pages/EventsEditPage.jsx
  src/adminPage/shared/components/SmallInput.jsx
  src/common/components/Input.jsx
  src/common/dataFetch/getQuery.js
  src/common/utils.js
Labels: feat

#101 [fix] 자잘한 오류 수정 및 카드게임 스켈레톤 UI 추가
  src/adminPage/features/eventEdit/FcfsInput.jsx
  src/adminPage/features/eventList/table/SearchResultItem.jsx
  src/common/dataFetch/fetchServer.js
  src/common/dataFetch/getQuery.js
  src/mainPage/features/fcfs/cardGame/CardGameSkeleton.jsx
  src/mainPage/features/fcfs/cardGame/index.jsx
Labels: fix

#104 [feat] 어드민 기대평 페이지 구현
  src/adminPage/features/comment/id/Comments.jsx
  src/adminPage/features/comment/id/DeleteButton.jsx
  src/adminPage/features/comment/id/Loading.jsx
  src/adminPage/features/comment/id/index.jsx
  src/adminPage/features/comment/mock.js
  src/adminPage/pages/CommentsIDPage.jsx
  src/common/mock/getRandomString.js
Labels: feat

#105 [feat] api 주소 수정, getDayDifference 함수 정의
  src/common/utils.js
  src/mainPage/features/interactions/index.jsx
  src/mainPage/features/interactions/mock.js
  src/mainPage/features/interactions/modal/InteractionAnswer.jsx
  src/mainPage/features/interactions/modal/InteractionModal.jsx
  src/mainPage/features/interactions/modal/joinEvent.js
Labels: feat

#106 [refactor] 코드 리팩터링
  .prettierrc
  src/common/constants.js
  src/common/utils.js
  src/mainPage/features/interactions/description/InteractionSlide.jsx
  src/mainPage/features/interactions/description/TapBar.jsx
  src/mainPage/features/interactions/index.jsx
  src/mainPage/features/interactions/modal/InteractionAnswer.jsx
  src/mainPage/features/interactions/modal/joinEvent.js
Labels: chore, refactor

#113 [feat] 어드민 기대평 여러가지
  src/adminPage/features/comment/id/Comments.jsx
  src/adminPage/features/comment/id/DeleteButton.jsx
  src/adminPage/features/comment/id/index.jsx
  src/adminPage/features/comment/mock.js
Labels: feat

#114 [feat] 단축 URL 복사 구현
  src/mainPage/features/interactions/mock.js
  src/mainPage/features/interactions/modal/InteractionAnswer.jsx
Labels: feat

#115 [feat, chore] 자잘한 것들 수정 및 성능 개선
  build.js
  package-lock.json
  package.json
  src/adminPage/features/eventEdit/businessLogic/FcfsData.js
  src/mainPage/App.jsx
  src/mainPage/features/comment/commentForm/index.jsx
  src/mainPage/features/comment/mock.js
  src/mainPage/features/detailInformation/DetailItem.jsx
  src/mainPage/features/fcfs/cardGame/Card.jsx
  src/mainPage/features/fcfs/description/DateEventPrize.jsx
  src/mainPage/features/fcfs/mock.js
  src/mainPage/features/header/Hamburger/Button.jsx
  src/mainPage/features/header/Hamburger/style.module.css
  src/mainPage/features/header/index.jsx
  src/mainPage/features/interactions/description/GiftDetail.jsx
  src/mainPage/features/interactions/description/InteractionSlide.jsx
  src/mainPage/features/simpleInformation/contentSection.jsx
  src/mainPage/shared/auth/mock.js
  src/mainPage/shared/auth/store.js
  src/mainPage/shared/components/ResetButton.jsx
  src/mainPage/shared/drawEvent/store.js
  src/mainPage/shared/realtimeEvent/store.js
  vite.config.js
Labels: fix, feat, refactor

#116 [refactor] 인터랙션 상태 전역으로 변경 및 리팩토링
  src/mainPage/features/comment/index.jsx
  src/mainPage/features/detailInformation/DetailSwiper.jsx
  src/mainPage/features/detailInformation/index.jsx
  src/mainPage/features/fcfs/cardGame/CardGame.jsx
  src/mainPage/features/fcfs/mock.js
  src/mainPage/features/fcfs/modals/FcfsLoseModal.jsx
  src/mainPage/features/interactions/description/GiftDetail.jsx
  src/mainPage/features/interactions/description/InteractionSlide.jsx
  src/mainPage/features/interactions/description/TapBar.jsx
  src/mainPage/features/interactions/index.jsx
  src/mainPage/features/interactions/modal/AnswerDescription.jsx
  src/mainPage/features/interactions/modal/InteractionAnswer.jsx
  src/mainPage/features/interactions/modal/InteractionModal.jsx
  src/mainPage/features/interactions/modal/buttons/MoveCommentButton.jsx
  src/mainPage/features/interactions/modal/buttons/ParticipateButton.jsx
  src/mainPage/features/interactions/modal/buttons/ShareButton.jsx
  src/mainPage/features/interactions/modal/buttons/ShowAnswerButton.jsx
  src/mainPage/features/interactions/modal/context.js
  src/mainPage/features/interactions/modal/joinEvent.js
  src/mainPage/shared/auth/store.js
  src/mainPage/shared/drawEvent/DrawEventFetcher.jsx
  src/mainPage/shared/drawEvent/store.js
Labels: fix, refactor

#119 [design] 비디오 재생 y좌표 임계값을 화면 크기에 따라 동적으로 계산
  src/mainPage/features/introSection/index.jsx
Labels: style

#120 [feat] 어드민 기대평 잡다 기능
  src/adminPage/features/comment/id/Comments.jsx
  src/adminPage/features/comment/id/index.jsx
  src/adminPage/features/comment/index.jsx
  src/adminPage/features/comment/mock.js
  src/adminPage/features/eventList/queryReducer.js
Labels: feat

#123 [modify] 로그아웃 기능 추가, 자잘한 버그 수정, 접근성 개선
  src/adminPage/features/eventEdit/index.jsx
  src/common/constants.js
  src/common/dataFetch/getQuery.js
  src/common/modal/modal.jsx
  src/common/modal/openModal.js
  src/common/modal/useFocusTrap.js
  src/mainPage/features/comment/autoScrollCarousel/index.jsx
  src/mainPage/features/comment/autoScrollCarousel/useAutoCarousel.js
  src/mainPage/features/comment/commentCarousel/CommentCarousel.jsx
  src/mainPage/features/comment/commentCarousel/CommentCarouselNoData.jsx
  src/mainPage/features/comment/modals/CommentNegativeModal.jsx
  src/mainPage/features/comment/modals/CommentNoUserModal.jsx
  src/mainPage/features/comment/modals/CommentSuccessModal.jsx
  src/mainPage/features/detailInformation/DetailSwiper.jsx
  src/mainPage/features/fcfs/cardGame/Card.jsx
  src/mainPage/features/fcfs/cardGame/CardGame.jsx
  src/mainPage/features/fcfs/cardGame/index.jsx
  src/mainPage/features/fcfs/modals/FcfsInvalidModal.jsx
  src/mainPage/features/fcfs/modals/FcfsLoseModal.jsx
  src/mainPage/features/fcfs/modals/FcfsWinModal.jsx
  src/mainPage/features/header/AuthButtonSection.jsx
  src/mainPage/features/header/Hamburger/Button.jsx
  src/mainPage/features/header/index.jsx
  src/mainPage/features/interactions/mock.js
  src/mainPage/features/interactions/modal/InteractionAnswer.jsx
  src/mainPage/features/interactions/modal/InteractionModal.jsx
  src/mainPage/features/interactions/modal/joinEvent.js
  src/mainPage/features/interactions/subsidy/index.jsx
  src/mainPage/features/interactions/v2l/Puzzle.jsx
  src/mainPage/features/interactions/v2l/PuzzlePiece.jsx
  src/mainPage/features/interactions/v2l/utils.js
  src/mainPage/features/qna/QnAArticle.jsx
  src/mainPage/shared/auth/AuthButton.jsx
  src/mainPage/shared/auth/Logout/LogoutAlertModal.jsx
  src/mainPage/shared/auth/Logout/LogoutConfirmModal.jsx
  src/mainPage/shared/auth/store.js
  src/mainPage/shared/components/AlertModalContainer.jsx
  src/mainPage/shared/components/NoServerModal.jsx
  src/mainPage/shared/components/ResetButton.jsx
  src/mainPage/shared/drawEvent/DrawEventFetcher.jsx
  src/mainPage/shared/drawEvent/store.js
  src/mainPage/shared/realtimeEvent/store.js
Labels: fix, feat

#126 [fix] 화면 길이 변경되어도 비디오 타임라인 정상 작동
  src/mainPage/features/introSection/index.jsx
Labels: fix

#127 [feat] 어드민 유저 조회 페이지 구현
  src/adminPage/App.jsx
  src/adminPage/features/comment/index.jsx
  src/adminPage/features/users/Loading.jsx
  src/adminPage/features/users/Users.jsx
  src/adminPage/features/users/index.jsx
  src/adminPage/features/users/mock.js
  src/adminPage/mock.js
  src/adminPage/pages/UsersPage.jsx
  src/adminPage/shared/components/NavBar.jsx
  src/common/constants.js
Labels: fix, feat

#128 [feat] 인터랙션 키보드 접근성 개선
  admin.html
  index.html
  public/font/HyundaiSansTextKROTFBold.woff2
  public/font/HyundaiSansTextKROTFMedium.woff2
  public/font/HyundaiSansTextKROTFRegular.woff2
  public/font/fonts.css
  src/adminPage/features/eventDetail/drawButton/DrawResultModal.jsx
  src/adminPage/features/eventDetail/drawButton/useScrollControl.js
  src/adminPage/index.css
  src/common/components/PhoneInput.jsx
  src/common/utils.js
  src/mainPage/features/interactions/description/InteractionSlide.jsx
  src/mainPage/features/interactions/description/TapBar.jsx
  src/mainPage/features/interactions/distanceDriven/index.jsx
  src/mainPage/features/interactions/distanceDriven/useDeviceRatio.js
  src/mainPage/features/interactions/distanceDriven/usePointDrag.js
  src/mainPage/features/interactions/fastCharge/index.jsx
  src/mainPage/features/interactions/fastCharge/useDialDrag.js
  src/mainPage/features/interactions/mock.js
  src/mainPage/features/interactions/univasalIsland/Phone.jsx
  src/mainPage/features/interactions/univasalIsland/index.jsx
  src/mainPage/features/interactions/univasalIsland/reducer.js
  src/mainPage/features/interactions/univasalIsland/useIslandDrag.js
  src/mainPage/features/introSection/index.jsx
  src/mainPage/index.css
  src/mainPage/shared/eventDescription/EventDetail.jsx
  src/mainPage/shared/hooks/useA11yDrag.js
  src/mainPage/shared/hooks/useMountDragEvent.js
Labels: feat

#130 [fix] 잡다하게 수정
  src/adminPage/features/comment/id/Comments.jsx
  src/adminPage/features/comment/index.jsx
  src/adminPage/features/eventEdit/FcfsInput/FcfsItemInput.jsx
  src/mainPage/shared/auth/requestAuthCode.js
Labels: fix

#129 [feat] V2L, 보조금 인터랙션 키보드 접근성 추가
  index.html
  public/font/HyundaiSansTextKROTFBold.otf
  public/font/HyundaiSansTextKROTFBold.woff
  public/font/HyundaiSansTextKROTFBold.woff2
  public/font/HyundaiSansTextKROTFMedium.otf
  public/font/HyundaiSansTextKROTFMedium.woff
  public/font/HyundaiSansTextKROTFMedium.woff2
  public/font/HyundaiSansTextKROTFRegular.otf
  public/font/HyundaiSansTextKROTFRegular.woff
  public/font/HyundaiSansTextKROTFRegular.woff2
  public/font/fonts.css
  src/adminPage/index.css
  src/common/constants.js
  src/mainPage/features/comment/commentForm/index.jsx
  src/mainPage/features/comment/mock.js
  src/mainPage/features/fcfs/cardGame/Card.jsx
  src/mainPage/features/fcfs/mock.js
  src/mainPage/features/header/Hamburger/Button.jsx
  src/mainPage/features/interactions/content.json
  src/mainPage/features/interactions/description/GiftDetail.jsx
  src/mainPage/features/interactions/description/InteractionSlide.jsx
  src/mainPage/features/interactions/distanceDriven/index.jsx
  src/mainPage/features/interactions/distanceDriven/usePointDrag.js
  src/mainPage/features/interactions/fastCharge/index.jsx
  src/mainPage/features/interactions/fastCharge/useDialDrag.js
  src/mainPage/features/interactions/mock.js
  src/mainPage/features/interactions/modal/InteractionModal.jsx
  src/mainPage/features/interactions/modal/joinEvent.js
  src/mainPage/features/interactions/subsidy/index.jsx
  src/mainPage/features/interactions/univasalIsland/Phone.jsx
  src/mainPage/features/interactions/univasalIsland/index.jsx
  src/mainPage/features/interactions/univasalIsland/reducer.js
  src/mainPage/features/interactions/univasalIsland/style.module.css
  src/mainPage/features/interactions/univasalIsland/useIslandDrag.js
  src/mainPage/features/interactions/univasalIsland/utils.js
  src/mainPage/features/interactions/v2l/Puzzle.jsx
  src/mainPage/features/interactions/v2l/PuzzlePiece.jsx
  src/mainPage/features/interactions/v2l/businessLogic/PieceData.js
  src/mainPage/features/interactions/v2l/businessLogic/constants.js
  src/mainPage/features/interactions/v2l/businessLogic/generateRandom.js
  src/mainPage/features/interactions/v2l/businessLogic/reducer.js
  src/mainPage/features/interactions/v2l/businessLogic/usePuzzleKeyMount.js
  src/mainPage/features/interactions/v2l/businessLogic/utils.js
  src/mainPage/features/interactions/v2l/constants.js
  src/mainPage/features/interactions/v2l/index.jsx
  src/mainPage/features/introSection/LineHighlight.jsx
  src/mainPage/features/introSection/index.jsx
  src/mainPage/features/qna/QnAArticle.jsx
  src/mainPage/features/simpleInformation/contentSection.jsx
  src/mainPage/index.css
  src/mainPage/shared/auth/AuthCode/index.jsx
  src/mainPage/shared/auth/AuthModal.jsx
  src/mainPage/shared/auth/InfoInput/index.jsx
  src/mainPage/shared/auth/UserFind/index.jsx
  src/mainPage/shared/auth/Welcome/index.jsx
  src/mainPage/shared/components/AlertModalContainer.jsx
  src/mainPage/shared/realtimeEvent/store.js
Labels: fix, feat

#133 [fix] 긴급수정
  src/adminPage/features/comment/id/Comments.jsx
  src/adminPage/features/users/Users.jsx
  src/mainPage/features/fcfs/cardGame/CardGame.jsx
  src/mainPage/features/fcfs/mock.js
  src/mainPage/shared/auth/UserFind/requestLogin.js
  src/mainPage/shared/auth/mock.js
Labels: fix

#135 [fix] 어드민 빌드 환경에서 /events/(id)를 새로고침하면 404 에러가 뜨는 버그 수정
  packages/adminPage/build.js
  packages/adminPage/public/robots.txt
  packages/adminPage/vercel.json
Labels: fix

#136 [feat] 어드민 유저 검색 관련
  packages/adminPage/src/App.jsx
  packages/adminPage/src/features/users/Users.jsx
  packages/adminPage/src/features/users/index.jsx
Labels: feat

#137 [fix] 어드민 페이지 관련 일부 에러 수정
  packages/adminPage/build.js
  packages/adminPage/src/features/eventDetail/drawButton/DrawButton.jsx
  packages/adminPage/src/features/eventDetail/drawButton/mock.js
  packages/adminPage/src/features/eventList/DeleteButton.jsx
  packages/adminPage/src/features/eventList/mock.js
  packages/adminPage/src/features/eventList/table/SearchResultItem.jsx
  packages/adminPage/src/features/eventList/table/index.jsx
  packages/adminPage/src/shared/serverTime/EventStatus.js
  packages/common/sharedAssetRouter.js
  packages/common/src/components/Checkbox.jsx
  packages/common/src/constants.js
  packages/mainPage/src/features/detailInformation/DetailSwiper.jsx
  packages/mainPage/src/features/interactions/index.jsx
Labels: fix

#142 [chore] 어드민 유저 검색창 placeholder 문구 수정
  packages/adminPage/src/features/users/index.jsx
Labels: chore

#143 [fix, docs] 리드미 수정 및 약간의 버그 수정
  README.md
  package-lock.json
  package.json
  packages/adminPage/build.js
  packages/adminPage/index.html
  packages/adminPage/vite.config.js
  packages/common/package.json
  packages/common/src/components/PhoneInput.jsx
  packages/common/src/utils.js
  packages/mainPage/build.js
  packages/mainPage/index.html
  packages/mainPage/package.json
  packages/mainPage/public/images/fcfsBackground.webp
  packages/mainPage/public/images/thumbnails.png
  packages/mainPage/src/features/fcfs/cardGame/CardGame.jsx
  packages/mainPage/src/features/fcfs/index.jsx
  packages/mainPage/src/features/interactions/index.jsx
  packages/mainPage/src/features/introSection/index.jsx
  packages/mainPage/src/features/simpleInformation/index.jsx
  packages/mainPage/src/shared/auth/AuthModal.jsx
  packages/mainPage/src/shared/drawEvent/store.js
  packages/mainPage/vite.config.js
  public/favicon/android-chrome-192x192.png
  public/favicon/android-chrome-512x512.png
  public/favicon/apple-touch-icon.png
  public/favicon/favicon-16x16.png
  public/favicon/favicon-32x32.png
  public/favicon/favicon.ico
  public/favicon/site.webmanifest
  public/vite.svg
  vite-devRouter.js
Labels: fix, docs

#144 1.0.1 업데이트
  README.md
  package-lock.json
  package.json
  packages/adminPage/build.js
  packages/adminPage/index.html
  packages/adminPage/src/features/users/index.jsx
  packages/adminPage/vite.config.js
  packages/common/package.json
  packages/common/src/components/PhoneInput.jsx
  packages/common/src/utils.js
  packages/mainPage/build.js
  packages/mainPage/index.html
  packages/mainPage/package.json
  packages/mainPage/public/images/fcfsBackground.webp
  packages/mainPage/public/images/thumbnails.png
  packages/mainPage/src/features/fcfs/cardGame/CardGame.jsx
  packages/mainPage/src/features/fcfs/index.jsx
  packages/mainPage/src/features/interactions/index.jsx
  packages/mainPage/src/features/introSection/index.jsx
  packages/mainPage/src/features/simpleInformation/index.jsx
  packages/mainPage/src/shared/auth/AuthModal.jsx
  packages/mainPage/src/shared/drawEvent/store.js
  packages/mainPage/vite.config.js
  public/favicon/android-chrome-192x192.png
  public/favicon/android-chrome-512x512.png
  public/favicon/apple-touch-icon.png
  public/favicon/favicon-16x16.png
  public/favicon/favicon-32x32.png
  public/favicon/favicon.ico
  public/favicon/site.webmanifest
  public/vite.svg
  vite-devRouter.js
Labels: fix

#147 [fix] 어드민 유저 검색에서 검색 시 페이지 1로 초기화
  packages/adminPage/src/features/users/Users.jsx
  packages/adminPage/src/features/users/index.jsx
Labels: fix

#148 [fix] 어드민 기대평 검색에서 새 문자열 검색 시 페이지 1로 초기화
  packages/adminPage/src/features/comment/id/Comments.jsx
  packages/adminPage/src/features/comment/id/index.jsx
Labels: fix

#149 1.0.1.2 핫픽스
  packages/adminPage/src/features/comment/id/Comments.jsx
  packages/adminPage/src/features/comment/id/index.jsx
  packages/adminPage/src/features/users/Users.jsx
  packages/adminPage/src/features/users/index.jsx
Labels: fix

#150 [docs] 리드미 내용 추가
  README.md
Labels: docs

#151 리드미 내용수정
  README.md
Labels: docs
